---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: notejam-app
    hostname: notejam-app
    image: ubuntu:18.04
    pull: true
    exposed_ports:
      - 3000/tcp
    published_ports:
      - 0.0.0.0:3000:3000/tcp
    env:
      FOO: bar
    restart_policy: on-failure
    restart_retries: 1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
