imports:
    - { resource: config_dev.yml }

# Test doctrine Configuration
#doctrine:
    #dbal:
        #driver: pdo_sqlite
        #path: :memory:
        #memory: true
        #charset:  UTF8
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

liip_functional_test: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test: ~
