security:
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    providers:
        user_db:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        main:
            pattern: ^/*
            provider: user_db
            form_login:
                login_path: /signin
                check_path: /login_check
                username_parameter: form[email]
                password_parameter: form[password]
                default_target_path: /
                remember_me: true
            logout:
                path: /signout
                target: /signin
            remember_me:
                key: MiPassphrase
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
    access_control:
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: /signin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /settings, roles: ROLE_USER }
        - { path: /notes, roles: ROLE_USER }
        - { path: /pads, roles: ROLE_USER }
        - { path: /, roles: ROLE_USER }
