version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notejam
      - MYSQL_USER=nj
      - MYSQL_PASSWORD=password
  migration:
    depends_on:
      - db
    build:
      context: .
    command: ["db.py"]
    environment:
      - MYSQL_HOST=db:3306
      - MYSQL_DATABASE=notejam
      - MYSQL_USER=nj
      - MYSQL_PASSWORD=password
  app:
    depends_on:
      - migration
    command: ["runserver.py", "--host=0.0.0.0"]
    build:
      context: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      - MYSQL_HOST=db:3306
      - MYSQL_DATABASE=notejam
      - MYSQL_USER=nj
      - MYSQL_PASSWORD=password
