name: Staging

on:
  push:
    branches: [ staging ]
tab
 workflow_dispatch:

jobs:
    deploy:
    
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCR_DEV_PROJECT_ID }}/${{ secrets.GCR_DEV_APP_NAME }}-ver-${{ github.sha }}
        steps:
        
        - name: Check Out Repo 
          uses: actions/checkout@v2
        
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCR_DEV_PROJECT_ID }}
            service_account_email: ${{ secrets.GCR_DEV_SERVICE_NAME }}
            service_account_key: ${{ secrets.GCR_DEV_KEY }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME
          
        - name: Run Test
          run: python django/notejam/manage.py test
          
        - name: Push Docker image
          run: docker push $IMAGE_NAME

   #     - name: Deploy Docker image
   #       run: gcloud run deploy ${{ secrets.PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed
